/**
 * Copyright (C) 2026  HardenedLinux community
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Allow basic syscalls needed for typical execution
int syscalls[] = {
  SCMP_SYS (read),
  SCMP_SYS (write),
  SCMP_SYS (open),
  SCMP_SYS (openat),
  SCMP_SYS (openat2),
  SCMP_SYS (prlimit64),
  SCMP_SYS (close),
  SCMP_SYS (mmap),
  SCMP_SYS (munmap),
  SCMP_SYS (mprotect),
  SCMP_SYS (brk),
  SCMP_SYS (exit_group),
  SCMP_SYS (exit),
  SCMP_SYS (fstat),
  SCMP_SYS (lseek),
  SCMP_SYS (ioctl),
  SCMP_SYS (writev),
  SCMP_SYS (readv),
  SCMP_SYS (clock_gettime),
  SCMP_SYS (getrandom),
  SCMP_SYS (getpid),
  SCMP_SYS (getppid),
  SCMP_SYS (gettid),
  SCMP_SYS (geteuid),
  SCMP_SYS (getegid),
  SCMP_SYS (getppid),
  SCMP_SYS (futex),
  SCMP_SYS (nanosleep),
  SCMP_SYS (dup),
  SCMP_SYS (dup2),
  SCMP_SYS (dup3),
  SCMP_SYS (pipe),
  SCMP_SYS (pipe2),
  SCMP_SYS (clone),
  SCMP_SYS (fork),
  SCMP_SYS (vfork),
  SCMP_SYS (execve),
  SCMP_SYS (execveat),
  SCMP_SYS (access),
  SCMP_SYS (faccessat),
  SCMP_SYS (faccessat2),
  SCMP_SYS (stat),
  SCMP_SYS (lstat),
  SCMP_SYS (readlink),
  SCMP_SYS (readlinkat),
  SCMP_SYS (uname),
  SCMP_SYS (sched_yield),
  SCMP_SYS (getcwd),
  SCMP_SYS (chdir),
  SCMP_SYS (fchdir),
  SCMP_SYS (mkdir),
  SCMP_SYS (mkdirat),
  SCMP_SYS (rmdir),
  SCMP_SYS (unlink),
  SCMP_SYS (unlinkat),
  SCMP_SYS (rename),
  SCMP_SYS (renameat),
  SCMP_SYS (link),
  SCMP_SYS (symlink),
  SCMP_SYS (getdents),
  SCMP_SYS (getdents64),
  SCMP_SYS (ftruncate),
  SCMP_SYS (truncate),
  SCMP_SYS (fcntl),
  SCMP_SYS (flock),
  SCMP_SYS (sendfile),
  SCMP_SYS (copy_file_range),
  SCMP_SYS (capget),
  SCMP_SYS (capset),
  SCMP_SYS (prctl),
  SCMP_SYS (arch_prctl),
  SCMP_SYS (set_tid_address),
  SCMP_SYS (set_robust_list),
  SCMP_SYS (rt_sigaction),
  SCMP_SYS (rt_sigprocmask),
  SCMP_SYS (rt_sigreturn),
  SCMP_SYS (sigaltstack),
  SCMP_SYS (madvise),
  SCMP_SYS (mlock),
  SCMP_SYS (munlock),
  SCMP_SYS (mincore),
  SCMP_SYS (getegid),
  SCMP_SYS (geteuid),
  SCMP_SYS (getgid),
  SCMP_SYS (getuid),
  SCMP_SYS (getresgid),
  SCMP_SYS (getresuid),
  SCMP_SYS (getgroups),
  SCMP_SYS (setgroups),
  SCMP_SYS (setgid),
  SCMP_SYS (setuid),
  SCMP_SYS (setresgid),
  SCMP_SYS (setresuid),
  SCMP_SYS (setpgid),
  SCMP_SYS (getpgid),
  SCMP_SYS (setsid),
  SCMP_SYS (getsid),
  SCMP_SYS (wait4),
  SCMP_SYS (waitpid),
  SCMP_SYS (kill),
  SCMP_SYS (tkill),
  SCMP_SYS (socket),
  SCMP_SYS (connect),
  SCMP_SYS (bind),
  SCMP_SYS (listen),
  SCMP_SYS (accept),
  SCMP_SYS (accept4),
  SCMP_SYS (setsockopt),
  SCMP_SYS (getsockopt),
  SCMP_SYS (sendto),
  SCMP_SYS (recvfrom),
  SCMP_SYS (sendmsg),
  SCMP_SYS (recvmsg),
  SCMP_SYS (shutdown),
  SCMP_SYS (getpeername),
  SCMP_SYS (getsockname),
  SCMP_SYS (epoll_create),
  SCMP_SYS (epoll_ctl),
  SCMP_SYS (epoll_wait),
  SCMP_SYS (eventfd),
  SCMP_SYS (timerfd_create),
  SCMP_SYS (timerfd_settime),
  SCMP_SYS (signalfd),
  SCMP_SYS (newfstatat),
  SCMP_SYS (statx),
  SCMP_SYS (getcpu),
  SCMP_SYS (sched_getaffinity),
  SCMP_SYS (sched_setaffinity),
  SCMP_SYS (get_mempolicy),
  SCMP_SYS (mbind),
  SCMP_SYS (migrate_pages),
  SCMP_SYS (landlock_create_ruleset),
  SCMP_SYS (landlock_add_rule),
  SCMP_SYS (landlock_restrict_self),
  SCMP_SYS (set_tid_address),
  SCMP_SYS (set_robust_list),
  SCMP_SYS (rseq),
  SCMP_SYS (clone3),
  SCMP_SYS (pread64),
  SCMP_SYS (pwrite64),
};
